package com.edulab.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("edu_right", "rightId", Right.class);
		arp.addMapping("edu_role", "roleId", Role.class);
		arp.addMapping("edu_role_right", "id", RoleRight.class);
		arp.addMapping("edu_user", "id", User.class);
		arp.addMapping("edu_user_auths", "id", UserAuths.class);
		arp.addMapping("edu_user_role", "id", UserRole.class);
	}
}

