package com.edulab.model;

import com.edulab.model_base.BaseMenuRole;

import java.util.HashSet;
import java.util.Set;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MenuRole extends BaseMenuRole<MenuRole> {

    public static final MenuRole dao = new MenuRole();

    /**
     * Get Menu ID By Role IDS
     * @param roleIDs
     * @return
     */
    public Set<Integer> getMenuIDByRoleIDs(Set<Integer> roleIDs){
        String sql = "select * from edu_menu_role where role_id = ?";
        Set<Integer> menuID = new HashSet<Integer>();
        for (int id : roleIDs){
            Set<MenuRole> menuRoles = new HashSet<MenuRole>(find(sql, id));
            for (MenuRole menuRole: menuRoles){
                menuID.add(menuRole.getMenuId());
            }
        }
        return menuID;
    }
}
