package com.edulab.model;

import com.edulab.model_base.BaseMenu;

import java.util.HashSet;
import java.util.Set;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu> {

    public static final Menu dao = new Menu();

    /**
     * Get Top Menus By a set of menu id
     * @param menuID
     * @return
     */
    public Set<Menu> getMenusByMenuIds(Set<Integer> menuID, int menuLevel){
        String sql = "select * from edu_menu where menu_id = ?";
        Set<Menu> menus = new HashSet<Menu>();
        for (int id: menuID){
            Menu menu = findFirst(sql, id);
            if (menu != null && menu.getMenuLevel()==menuLevel){
                menus.add(menu);
            }
        }
        return menus;
    }
}
