package com.edulab.model;

import com.edulab.model_base.BaseRoleRight;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleRight extends BaseRoleRight<RoleRight> {

    public static final RoleRight dao = new RoleRight();

    /**
     * 根据传入的用户ID判断获取用户的权限列表
     * @param userId
     * @return
     */
    public Set<String> getRightsById(int userId){
        Set<String> rights = new HashSet();
        String sql = "select roleId from edu_user_role where userId = ?";
        List<UserRole> roleAll = UserRole.dao.find(sql,userId);
        for (int i =0; i <roleAll.size();i++){
            int roleId = roleAll.get(i).getRoleId();
            if (roleId != -1){
                int rightId = getRightIdByRoleId(roleId);
                String rightName = Right.dao.getRightNameById(rightId);
                if (rightName != null)
                    rights.add(rightName);
            }
        }
        return rights;
    }

    /**
     * 根据角色ID返回权限ID
     * @param roleId
     * @return -1表示不存在此角色对应的权限
     */
    public int getRightIdByRoleId(int roleId){
        String sql = "select rightId from edu_role_right where roleId = ?";
        RoleRight roleRights = findFirst(sql,roleId);
        return roleRights==null?-1:roleRights.getRightId();
    }
}
