package com.edulab.model_base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRight<M extends BaseRight<M>> extends Model<M> implements IBean {

	public M setRightId(java.lang.Long rightId) {
		set("rightId", rightId);
		return (M)this;
	}
	
	public java.lang.Long getRightId() {
		return getLong("rightId");
	}

	public M setRightName(java.lang.String rightName) {
		set("rightName", rightName);
		return (M)this;
	}
	
	public java.lang.String getRightName() {
		return getStr("rightName");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

}
