package com.edulab.model_base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserAuth<M extends BaseUserAuth<M>> extends Model<M> implements IBean {

	public M setAuthenId(java.lang.Integer authenId) {
		set("authen_id", authenId);
		return (M)this;
	}
	
	public java.lang.Integer getAuthenId() {
		return getInt("authen_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setIdentityType(java.lang.String identityType) {
		set("identity_type", identityType);
		return (M)this;
	}
	
	public java.lang.String getIdentityType() {
		return getStr("identity_type");
	}

	public M setInsideLogin(java.lang.Boolean insideLogin) {
		set("inside_login", insideLogin);
		return (M)this;
	}
	
	public java.lang.Boolean getInsideLogin() {
		return get("inside_login");
	}

	public M setIdentifier(java.lang.String identifier) {
		set("identifier", identifier);
		return (M)this;
	}
	
	public java.lang.String getIdentifier() {
		return getStr("identifier");
	}

	public M setSalt(java.lang.String salt) {
		set("salt", salt);
		return (M)this;
	}
	
	public java.lang.String getSalt() {
		return getStr("salt");
	}

	public M setCredential(java.lang.String credential) {
		set("credential", credential);
		return (M)this;
	}
	
	public java.lang.String getCredential() {
		return getStr("credential");
	}

}
