package com.edulab.model_base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRoleRight<M extends BaseRoleRight<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
		return (M)this;
	}
	
	public java.lang.Integer getRoleId() {
		return getInt("roleId");
	}

	public M setRightId(java.lang.Integer rightId) {
		set("rightId", rightId);
		return (M)this;
	}
	
	public java.lang.Integer getRightId() {
		return getInt("rightId");
	}

	public M setRightType(java.lang.Long rightType) {
		set("rightType", rightType);
		return (M)this;
	}
	
	public java.lang.Long getRightType() {
		return getLong("rightType");
	}

}
