package com.edulab.model_base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public M setMenuId(java.lang.Integer menuId) {
		set("menu_id", menuId);
		return (M)this;
	}
	
	public java.lang.Integer getMenuId() {
		return getInt("menu_id");
	}

	public M setMenuName(java.lang.String menuName) {
		set("menu_name", menuName);
		return (M)this;
	}
	
	public java.lang.String getMenuName() {
		return getStr("menu_name");
	}

	public M setMenuDescription(java.lang.String menuDescription) {
		set("menu_description", menuDescription);
		return (M)this;
	}
	
	public java.lang.String getMenuDescription() {
		return getStr("menu_description");
	}

	public M setMenuParentId(java.lang.Integer menuParentId) {
		set("menu_parent_id", menuParentId);
		return (M)this;
	}
	
	public java.lang.Integer getMenuParentId() {
		return getInt("menu_parent_id");
	}

	public M setMenuLevel(java.lang.Integer menuLevel) {
		set("menu_level", menuLevel);
		return (M)this;
	}
	
	public java.lang.Integer getMenuLevel() {
		return getInt("menu_level");
	}

	public M setMenuCreateTime(java.util.Date menuCreateTime) {
		set("menu_create_time", menuCreateTime);
		return (M)this;
	}
	
	public java.util.Date getMenuCreateTime() {
		return get("menu_create_time");
	}

}
